### ISSUE TITLE
missing input_select -  fan speed, aka vacuum_mode

### ISSUE THREAD

**Issue by luzik** [poisondima/Roidmi-EVE-Plus#5]
There is no way to set fan speed using this package

**Comment by kamil382** [comment]
or collect the dust ?

**Comment by poisondima** [comment]
The speed can be selected through the standard properties of the vacuum cleaner. Click on the status of the vacuum cleaner and there you can select the speed.
![изображение](https://user-images.githubusercontent.com/39500249/178756629-5be2ced6-78c8-4801-b002-038c37ccda63.png)
![изображение](https://user-images.githubusercontent.com/39500249/178757074-b7480fb3-e03e-4bd5-be94-390affcdbfca.png)

**Comment by luzik** [comment]
status link was quite hidden - not obvious, but yeah it does work.

**Comment by poisondima** [comment]
@luzik, I added two fields, now you can change.
![изображение](https://user-images.githubusercontent.com/39500249/179076268-c2afb967-5e15-4bab-9cee-a17d72261d51.png)

**Comment by luzik** [comment]
thx for sharing !

I also have two more questions..
1. sensor.vacuum_on is state of vacuum power ? if yes, then please consider adding device_class: power
2. I found https://github.com/al-one/hass-xiaomi-miot/issues/163#issuecomment-902067849 and trying combine it with
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/406
Do you have any suggestions about Roidmi Eve params ?
...this should allow selecting multiple rooms from map for cleaning

**Comment by poisondima** [comment]
My assumption that cleaning works locally is not correct. Room cleaning only works through the cloud.
I have multiple room cleaning configured like this:
```
      alias: "Кухня + Коридор + Прихожая"
      mode: single
      icon: mdi:broom
      sequence:
        - service: xiaomi_miot.call_action
          data:
            entity_id: vacuum.vacuum_cleaner_robot_cleaner
            siid: 14
            aiid: 1
            params: [2,"{\"mapId\":XXXXXXXXX,\"segmentId\":[5,7,3]}"]
```
