### ISSUE TITLE
Интенты

### ISSUE THREAD

**Issue by ildmgithub** [poisondima/Roidmi-EVE-Plus#7]
А как интенты прокинуть в Алису?
У меня фильтр стоит на список устройств. По умолчанию не зашли. Яндекс пишет нет новых устройств при попытке добавления.
А что добавить не понятно.

**Comment by poisondima** [comment]
Да, мой косяк, давно настраивал все эти intents.
1. Для работы нужно установить через HACS [Yandex.Station](https://github.com/AlexxIT/YandexStation) и настроить его
2. Подкинуть файл 'yandex_station.yaml' в 'packages'
3. Перезагрузить HA и убедиться, что появится объект 'media_player.yandex_intents'
4. После этого добавить в файл 'yandex_station.yaml':
```
  yandex_smart_home:
    filter: # не забудьте добавить другие, важные для вас, устройства
      include_entities:
        # этот плеер отвечает за работу `intents`
        - media_player.yandex_intents
```
5. В квазаре после синхронизации HA и Яндекса появится новое устройство:
![изображение](https://user-images.githubusercontent.com/39500249/199495565-53e60c94-5ce6-4495-81a6-6ca4a388bd8c.png)
6. И уже после этого смогут синхронизироваться intents
