### ISSUE TITLE
Отправка уведомлений в Телеграм бот

### ISSUE THREAD

**Issue by nemen89** [poisondima/Roidmi-EVE-Plus#8]
Добрый день. Подскажите пожалуйста, по пакеджу работает всё, кроме уведомлений в бот телеграмм. Как будто не создан скрипт. В пакетже его нет, помогите пожалуйста разобраться. Бот настроен.

**Comment by IvAn-72** [comment]
Бот точно настроен? У меня тоже не приходили уведомления в телегу.  Всё есть в xiaomi_vacuum.yaml
Я приводил к такому виду:
      action:
        - service: telegram_bot.send_message
          data_template:
            target:
              - !secret chat_id_group
            emoji: "\U0001F9F9"
            message: 'Пылесос начал уборку'
            sound: "auto"
chat_id_group - номер группы (или пользователя) должен быть прописан в secrets.yaml

**Comment by nemen89** [comment]
Вот такой тестовый скрипт работает.
      send_message_1:
        alias: Отправка через сервис уведомлений
        sequence:
        - service: notify.telegram_id_1
          data:
            message: "Текущее время - {{ states('sensor.time') }} . Все в порядке"


А скрипт 
telegram_bot.send_message даже не создаётся в списке сриптов

**Comment by nemen89** [comment]
Похоже нужно убирать notify

**Comment by IvAn-72** [comment]
В configuration.yaml 1 или 2 вариант. От этого зависит дальнейшее.
1.
```
 telegram_bot:
   - platform: polling
     api_key: !secret telegram_api
     allowed_chat_ids:
       - !secret chat_id_group
       - !secret chat_id_xxx1
       - !secret chat_id_xxx2

```
2.
```
 notify:
   - name: telegram
     platform: telegram
     chat_id: !secret chat_id_group
   - name: telegram_id_1
     platform: telegram
     chat_id: !secret chat_id_xxx1
   - name: telegram_id_2
     platform: telegram
     chat_id: !secret chat_id_xxx2

``` 
В secrets.yaml
```
# telegram
telegram_api: 
chat_id_group: 
chat_id_xxx1: 
chat_id_xxx2: 
```
